---
language: node_js
node_js:
  - 10.14.1

sudo: false

dist: trusty

env:
  - CXX=g++-4.8

addons:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - xvfb
    - g++-4.8
  chrome: stable

cache:
  npm: true

install:
  - npm install -g npm@6.4.1
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - ./scripts/ci-check.sh

notifications:
  email: false
